[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "nodejs_18",
  "npm"
]

[phases.install]
commands = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "npm ci"
]

[phases.build]
commands = ["npm run build"]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT}"
